### ISSUE TITLE
32bit compiling error

### ISSUE THREAD

**Issue by professorjamesmoriarty** [jarun/bcal#4] opened 2016-10-20 14:22 UTC
Not looked into great deal, but I decided to test on 32bit (I really should have before). And it's given an error. Two things, would you like me to disable that arch for now on aur+ppa packages?

And here is the build log https://launchpadlibrarian.net/290184010/buildlog_ubuntu-trusty-i386.bcal_1.4-1_BUILDING.txt.gz 

The important part is:

```
bcal.c: In function ‘converttb’:
bcal.c:406:21: error: ‘__uint128_t’ undeclared (first use in this function)
  maxuint_t bytes = (__uint128_t)(tb * 1000000000000);
                     ^
bcal.c:406:21: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by jarun** [comment] 2016-10-20 14:24
Please disable 32-bit for `bcal`. I will check this and get back.

**Comment by jarun** [comment] 2016-10-20 14:28
Also, the intention was to use 64-bit for `bcal` all the time. Do you think we really need 32-bit packages for it? I would document it (or fix it) depending on your opinion.

**Comment by professorjamesmoriarty** [comment] 2016-10-20 14:34
Personally be great fixing it if it's simple to address. But most people use 64bit.. I see no issue with only supporting 64bit arch. If you chose to do so I'd suggest mentioning on the readme somewhere.

**Comment by jarun** [comment] 2016-10-20 14:45
I agree it would be great to have a fix. But the problem is, there are too many ways to err around the boundary conditions in numerical calculations. I'm sure this wouldn't be the last one given the fact I am using a 64-bit OS myself. If I find someone writing unit test cases for `bcal` and testing them out over a 32-bit OS on docker I can definitely revisit it. But till then, I'll leave it documented.

I'll get back once I update this _limitation_ in the README and man page.

**Comment by jarun** [comment] 2016-10-20 16:01
Closing with commit https://github.com/jarun/bcal/commit/a046054ede2ea7cfcc54058010657ad5a69d1f51.

**Closed as completed by jarun** 2016-10-20 16:01 UTC
